import puppeteer from 'puppeteer-core'
const out = process.argv[2]
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist'], defaultViewport: { width: 1440, height: 900 } })
const page = await browser.newPage()
const errs = []
page.on('pageerror', (e) => errs.push(e.message))
await page.goto('http://localhost:5173/', { waitUntil: 'domcontentloaded' })
await page.waitForFunction(() => document.querySelector('.loader')?.dataset.done === 'true', { timeout: 60000 })
await new Promise((r) => setTimeout(r, 2500))
const st = () => page.evaluate(() => { const s = window.__store.getState(); return { view: s.view, input: s.input, loaded: s.loaded, phase: s.phase, lidOpen: s.lidOpen, lampOn: s.lampOn, hovered: s.hovered } })
const at = (name, off) => page.evaluate((n, o) => window.__project(n, o), name, off)
const click = async (name, off, label) => {
  const p = await at(name, off)
  await page.mouse.move(p.x, p.y)
  await new Promise((r) => setTimeout(r, 250))
  const hov = (await st()).hovered
  await page.mouse.click(p.x, p.y)
  await new Promise((r) => setTimeout(r, 2200))
  const s = await st()
  console.log(label.padEnd(28), JSON.stringify({ at: p, hoveredBefore: hov, ...s }))
  return s
}
await click('sign_about', [0.03, 0, 0], 'room: click About sign')
await page.keyboard.press('Escape'); await new Promise((r) => setTimeout(r, 1500))
await page.keyboard.press('Escape'); await new Promise((r) => setTimeout(r, 1500))
console.log('after 2x Esc'.padEnd(28), JSON.stringify(await st()))
await click('lamp_shade', null, 'room: click lamp')
await click('sleeve_learnhub', null, 'room: click LearnHub sleeve')
await new Promise((r) => setTimeout(r, 2500))
console.log('after cue'.padEnd(28), JSON.stringify(await st()))
await click('tt_btn_start', null, 'hifi: click start/stop')
await click('rx_knob_input', null, 'hifi: click input knob')
await click('rx_screen', null, 'hifi: click screen')
await page.screenshot({ path: out + '/click_screen.png' })
await click('sleeve_stream-f1', null, 'screen: click F1 sleeve?')
await new Promise((r) => setTimeout(r, 4000))
console.log('after swap'.padEnd(28), JSON.stringify(await st()))
await page.evaluate(() => window.__store.getState().set({ view: 'hifi' }))
await new Promise((r) => setTimeout(r, 2000))
await page.screenshot({ path: out + '/click_hifi.png' })
await page.evaluate(() => window.__store.getState().set({ view: 'room', lightMode: 'night' }))
await new Promise((r) => setTimeout(r, 3000))
await page.screenshot({ path: out + '/click_night.png' })
console.log('errors', errs)
await browser.close()
