// Touch-input checks on a phone-sized viewport: node tools/test-touch.mjs [url]
import puppeteer from 'puppeteer-core'
const url = process.argv[2] || 'http://localhost:5173'
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--use-angle=d3d11', '--enable-gpu'], protocolTimeout: 120000 })
const p = await b.newPage()
await p.emulate({ viewport: { width: 390, height: 844, deviceScaleFactor: 2, isMobile: true, hasTouch: true }, userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1' })
await p.goto(url, { waitUntil: 'domcontentloaded' })
await p.waitForFunction(() => document.querySelector('.loader')?.dataset.done === 'true', { timeout: 90000 })
await new Promise((r) => setTimeout(r, 2000))
const st = () => p.evaluate(() => { const s = window.__store.getState(); return { view: s.view, loaded: s.loaded, input: s.input, listOpen: s.listOpen } })
const tapText = async (sel, text) => {
  const el = (await p.$$(sel)).find(async () => true)
  const handles = await p.$$(sel)
  for (const h of handles) if ((await h.evaluate((e) => e.textContent.trim())) === text) return h.tap()
  throw new Error('no ' + text)
}
await tapText('.tabbar button', 'Records')
await new Promise((r) => setTimeout(r, 2500))
console.log('tab Records ->', JSON.stringify(await st()))
const sp = await p.evaluate(() => window.__project ? window.__project('sleeve_djq-str') : null)
console.log('sleeve screen pos', JSON.stringify(sp))
if (sp) await p.touchscreen.tap(sp.x, sp.y)
await new Promise((r) => setTimeout(r, 1200))
console.log('tap DJQ sleeve ->', JSON.stringify(await st()))
await tapText('.tabbar button', 'Receiver')
await new Promise((r) => setTimeout(r, 1200))
console.log('tab Receiver ->', JSON.stringify(await st()), 'mobile OS visible:', await p.$eval('.rx-mobile', (e) => !!e).catch(() => false))
await tapText('.rx-mobile .os-input', 'AUX')
await new Promise((r) => setTimeout(r, 500))
console.log('tap AUX ->', JSON.stringify(await st()))
await tapText('.tabbar button', 'Room')
await new Promise((r) => setTimeout(r, 1500))
const before = await p.evaluate(() => ({ x: 0 }))
await p.touchscreen.touchStart(250, 500)
for (let i = 0; i < 10; i++) await p.touchscreen.touchMove(250 - i * 15, 500)
await p.touchscreen.touchEnd()
await new Promise((r) => setTimeout(r, 300))
console.log('after drag ->', JSON.stringify(await st()))
await p.tap('.menu-toggle')
await new Promise((r) => setTimeout(r, 300))
await tapText('.controls button', 'List view')
await new Promise((r) => setTimeout(r, 500))
console.log('menu > List view ->', JSON.stringify(await st()))
await b.close()
